### PR TITLE
Add Draw API

### PR DESCRIPTION
**Pull request by Ruin0x11**
# Summary
Allows mods to draw shapes and images by using the HSP drawing calls. Mods can also create and free temporary buffers for copying to/from.

# Playtest script
```lua
function draw_chips(chip)
   local buf = Draw.reserve_temp_buffer(Draw.screen_width(), Draw.screen_height())
   local x = 0
   local count = 100
   for i=0,count do
      Draw.update_screen(false)
      Draw.set_buffer(buf)
      Draw.copy_region(0, 0, 0, Draw.screen_width(), Draw.screen_height(), 0, 0)
      Draw.set_buffer(0)
      for j=0,40 do
         for k=0,40 do
            Draw.chip("core.chara_chip#" .. chip, x + j * 10, k * 10)
         end
      end
      Draw.redraw(true)
      Draw.copy_region(buf, 0, 0, Draw.screen_width(), Draw.screen_height(), 0, 0)

      x = x + 1
      if Input.get_pressed_keybind() then
         return
      end
   end
   Draw.free_temp_buffer(buf)
end
```

# TODO
- [x] Created a binding in `lua_api.cpp` inside the appropriate namespace.
- [x] Set the binding on the correct table in `lua::init()`.
- [ ] Updated `.luacheckrc` with the new table value.
- [ ] Added LDoc documentation in `doc/api`.
- [ ] Added tests inside `tests/lua_api.cpp`.

### CODE REVIEW

**Comment by ki-foobar** [comment]
Because HSP's draw calls are too primitive, I have a plan to organize them, and provide well-capsulated APIs in `GUI` module. Currently, such primitive calls are directly used even in C++ codebase, so it is impossible to provide these "for humans" APIs now. I think, however, the `Draw` module will be replaced by others or rewritten drastically in the future.

**Comment by Ruin0x11** [comment]
Agreed. However, at least having the possibility to draw things means a UI module itself could be written in Lua in the meantime. Also, things like writing new animations become much easier.

**Comment by ki-foobar** [comment]
> Agreed. However, at least having the possibility to draw things means a UI module itself could be written in Lua in the meantime. Also, things like writing new animations become much easier.

That makes sense. It was not a good idea to totally replace such primitive APIs. But some functions which address very low level (e.g., `Draw.set_buffer()` in Lua  / `gsel()` in C++) will be substituted because they prevent me from refactoring code/introducing new graphical feature/investigating bugs.

**Comment by Ruin0x11** [comment]
Then maybe the buffer-related commands should be left out and instead require a buffer argument for each API call? I think it could help if the default buffer was restored after each drawing-related event also.

**Comment by ki-foobar** [comment]
Closed the PR because it is hard to merge it into the current develop.

**Pull request closed without merging**
