### PR TITLE
Add resolution switching option/fullscreen

### LINKED ISSUE #508: Support custom resolutions
# Details
Support resolutions other than 800x600 without stretching of the graphics.

# Implementation note
There are multiple ways of going about this.
1. Choose from a supported list of standard resolutions.
2. Allow the user to resize the game window arbitrarily.

# Variants having this feature
Elona+

### PR DESCRIPTION
**Pull request by Ruin0x11**
# Related Issues

Close #508.

# Summary
Adds a resolution switching option based on polling the available display modes through SDL. Also adds fullscreen/desktop fullscreen options. Now ElonaFoobar can be played in true fullscreen.

# TODO
- [x] Test on Windows.
- [x] Test on macOS (with hi-DPI).

### CODE REVIEW

**Comment by Ruin0x11** [comment]
- It doesn't seem to respect hiDPI, meaning the largest resolution on macOS is cut off past the end of the screen in fullscreen mode.
- The fullscreen function in macOS doesn't work. This is because the window is initialized with 800x600 resolution because the supported window modes aren't known by the time the application is started.

**Comment by Ruin0x11** [comment]
The performance loss was caused by increasing the size of the temporary texture to 4096x4096 pixels. The reason was the text window was being copied with `gcopy` in the message updating routines, but the buffer region wasn't large enough to fit in the temporary texture, causing stretching glitches. The machine tested on used integrated graphics.

For now, whenever this gets merged, the text window width could be limited to around 1000 pixels, the current temporary texture width. Changing the temporary texture size seems to have major implications for rendering performance. In the distant future, the rendering system could be overhauled with something like OpenGL ES to avoid these issues.

**Comment by Ruin0x11** [comment]
I added another temporary texture for texture copies bigger than 1024 pixels. This only really gets used for the text window and the fullscreen backgrounds. It improves performance back to where it was.

**Comment by ki-foobar** [comment]
It seems to work well. I'm excited to be able to play Elona in such a big screen! Thank you.

**Pull request merged**
