### PR TITLE
Add a testsuite and savedata tests

### LINKED ISSUE #332: Add a testsuite
# Details
For things like save game serialization and mods, having a test suite to catch errors becomes critical. It would be difficult to manually playtest things like handling arbitrary user inputted scripts, testing serialization of mod data, migrating save data between old and new versions of mods, and other new features. At the very least the serialization portion should be tested to make sure the user doesn't loose data. Also, if we create a save migrater from OO then that would have to be tested, and I would definitely prefer to handle that automatically.

We could also catch regressions in user file formats. I recall that Elona+ had a regression caused by a custom talk format specifier changing, causing many user complaints. The response was to just convert the files manually and you'd have full compatibility between the two versions. I'd prefer to avoid things like this.

To simplify things, the tests could be partially implemented in Lua where possible. That would require the Lua prototype changes to be merged first, but I think that would be fine if it can be put under test immediately after.

### PR DESCRIPTION
**Pull request by Ruin0x11**
# Related Issues

Closes #332.

# Details

Adds a testsuite and sets it up to be run under continuous integration.
- Added the [Catch2](https://github.com/catchorg/Catch2) unit test library for creating a test harness executable.
- Added a starting testsuite testing save compatibility with a known good savefile.
- Added an index counter for items and characters so their index into the global arrays can be retrieved from a `character`/`item` struct. This will be used for communicating between legacy code using integers and new code using struct references.
- Refactored some functions related to serialization.
- Refactored parts of `snail` depending on SDL to be compiled with a macro define for regular or headless. This is because the overhead of having a virtual renderer class would be too much. All SDL-specific code now lives in `snail`.
- Added a headless rendering toggle to avoid having to initialize SDL under continuous integration.

The lines changed count is misleading. Only about 2,278 lines of code were actually changed. The majority of the count is made up of the testing save files and the Catch2 header.

# TODO
- [x] Fix .app bundle breakage on macOS.
- [x] Rename `idx` to `index`.
- [x] Make tests pass on all three platforms.

### CODE REVIEW

**Comment by ki-foobar** [comment]
> Added an index counter for items and characters so their index into the global arrays can be retrieved from a character/item struct. This will be used for communicating between legacy code using integers and new code using struct references.

That's very nice! It sounds good idea to add index field for refactoring with keeping original behavior.

**Comment by Ruin0x11** [comment]
Actually I'm not sure it's possible to run anything on the remote servers unless the original assets are available. Perhaps we could download them and remove them when finished.

**Comment by Ruin0x11** [comment]
Looks like we'll have to add a flag for disabling audio if the executable is running in CI, because on Linux there is no audio output available. I already added a flag to prevent a segfault when running in test mode around the audio init calls, so I'll change those to disable audio.

In the future we could consider abstracting `snail` to have a headless mode so there will be no need to initialize anything SDL-related.

**Comment by Ruin0x11** [comment]
Now it seems the SDL video driver is failing even after setting the renderer to `dummy`. Looks like a headless renderer will become necessary to merge this.

**Comment by Ruin0x11** [comment]
@ki-foobar This should be good to review.

**Comment by ki-foobar** [comment]
I see, will do.

**Comment by ki-foobar** [comment]
It seems to work well. Thank you for your awesome work!

**Pull request merged**
