### PR TITLE
Add code guidelines learned from working on the codebase

### PR DESCRIPTION
**Pull request by Ruin0x11**
# Summary
Adds some code style guidelines to `CONTRIBUTING.md`. Some of these are just opinions, but they could be useful for maintaining the consistency of the codebase if more people choose to contribute and more things are refactored.

### CODE REVIEW

**Comment by ki-foobar** [comment]
That's nice. I agree with all of the contents so far.
I think it is better to create a new file for coding style guide because the section is a bit long.

**Comment by Ruin0x11** [comment]
Okay, I'll do so.

**Comment by ki-foobar** [comment]
I agree with most of them, but I want to point out some trivial things.

> We use `snake_case` as it was inherited from the original HSP source.

It seems that Noa used camel case in the original source. HSP compiler ignores case and its decompiler converts all symbols to lower case. You can see part of the original source code [here](https://wikiwiki.jp/elonabugfix/chara_func.hsp).

The reason why I have used snake case is that I prefer it to camel case.

> Make functions/variables private to the current file `static` and prefix their names with `_` to make them distinct.

Currently, I use anonymous namespace instead of `static` qualifier.

**Comment by ki-foobar** [comment]
Merged. Thank you.

**Comment by ki-foobar** [comment]
Why wasn't it marked as "Merged" automatically? Anyway, it was merged into `develop` successfully.

**Pull request closed without merging**
