### PR TITLE
Introduce Lua API for experimenting/playtesting

### LINKED ISSUE #434: Wish for skill levels(for debugging)
# Details

All of these wish are available only in wizard mode.

- "NUMBER skill SKILLNAME": Makes your {SKILLNAME}' level {NUMBER}. Example:
  - "2000 skill traveling": Your traveling skills grows up to 2000Lv.
  - "0 skill performance": You lose performance skill.

### PR DESCRIPTION
**Pull request by Ruin0x11**
# Related Issues

Closes #434. (You can use the API to set skill levels on startup)

# Summary
Adds the Lua API prototype to the game. The culmination of a good amount of work, this allows programmatically adding to the game's behavior by allowing the injection of custom code in various places.

The primary purpose of this change is not to be able to create mods, but to instead allow playtesting of features/bugs with the new startup script feature. At game load, you can now optionally run a Lua script to get to a specific game state. There are currently basic APIs for many common behaviors, and they will probably end up changing over time. For example, the skill API will need to be refactored to pass references to skill objects.

Also, some edge cases like copying characters/items are yet to be worked out. But for scripts that run on startup only, it should be fine. More robust data lifecycle handling will come as another change. I want to be able to regression test the copying/moving behavior properly in a separate change,

The API remains largely detached from most of the code. Only spots where the event hooks can run have direct contact with the API engine. This shouldn't cause differences in behavior without any scripts loaded. Of course, this should be playtested first.

See the individual commits for a breakdown of what's been added.

# Structure
## API engine
The core API engine in `lua_env.cpp` is responsible for loading and managing script sandboxes. Each script runs in its own Lua environment with a whitelist of available functions, so dangerous things like `loadstring` can't be run. It also has helpers for C++ object lifecycles and ways to access the individual API engine components.

## API manager
Stores a table in a separate Lua environment containing the core API bindings. The separate API tables can be passed to completely separate Lua environments as references by calling the Lua function `Elona.require`. For example, to access the `Map` API, one would do `local Map = Elona.require("Map")`. This avoids polluting the global namespace and potentially allows for programmatically extending the available API tables.

## Event manager
Stores and triggers event callbacks that are registered from Lua. Adds the `Event` API to the API manager. Templates are used so any arbitrary type/number of arguments can be passed from C++.

## Handle manager
Tracks references to C++ objects that are used in Lua by creating "handles" to them. Handles are Lua tables with a flag for validity and the underlying C++ reference. When C++ objects are created or invalidated, the corresponding handle is created or invalidated in Lua by this manager. If a handle is invalidated, any attempt to call an API method on it or pass it into an API function will raise an error. This is why it's important to ensure the handles are properly invalidated from C++, as that is where the object lifetimes are tracked.

## Store
This is a C++ `unordered_map` which is bound to each script environment and has awareness of possible Lua types. It will allow for relatively painless serialization of script-related data when the game is saved. The idea will be that any script data that needs to be saved can be transparently added on top of the original game data, without needing to modify C++ code and break save compatibility. This assumes that users will not remove mods later, but I believe that's a reasonable assumption to make for the time being.

It can be used from Lua like so:

```lua
function on_chara_created(chara)
  Store.stuff[chara.index] = Rand.rnd(42)
end

function on_chara_moved(chara)
  GUI.txt("My stuff is " .. Store.stuff[chara.index] .. " ")
end

Event.register(Event.EventKind.CharaCreated, on_chara_created)
Event.register(Event.EventKind.CharaMoved, on_chara_moved)
```

Serialization is not currently implemented and is planned for later.

## Documentation
Documentation is placed inside `doc/`. It can be rendered to `bin/doc` using `make ldoc`. To render it, `ldoc` is required, which can be installed through `luarocks`.

## Examples
[Here](https://gist.github.com/Ruin0x11/69d6dea349e97831351ed09472dfc022) is a script for testing all the magic in the game, including potions, scrolls and rods of all curse types. To use it, place it in the `data/script` folder and add this value to `config.json`:

```json
    "startup_script": "all_magic.lua"
```

Starting the game should run the script. Then, damage the yeek to get potions, the mummy to get scrolls, and the blade to get rods.

[Here](https://gist.github.com/Ruin0x11/01250844804d3d015590f78753d99aef) is another script for stress-testing AI/rendering.

# Changelist
- Added the `sol2` Lua binding. This allows for complex operations like creating isolated Lua environments without the need to use raw Lua state pointers.
- Added the core API engine in `lua_env/`.
- Added places for event hooks to run in various places.
- Refactored some object deletion routines to interact with the API properly.
- Added API documentation.
- Added many tests for the Lua API engine.
- Added benchmarks for event callback handling.

# TODO
- [x] Merge and rebase off of #438.
- [x] Change Lua error reporting to not use stdout and instead output to the game screen/log if not running in headless mode.
- [x] Check functions in `Rand` API.
- [x] Make Lua error reporting far less verbose when testing in headless mode.
- [x] Refactor item deletion so the corresponding Lua hook behaves properly.
- [x] Attach and run some playtest scripts giving an idea of the usefulness of the feature.
- [x] Playtest without any event hooks loaded.
- [x] Make sure tables returned by `Elona.require` are read-only.
- [x] Attach some benchmark results.
- [x] Ensure API examples are up to date.
- [x] Remove all extraneous TODOs/temporary comments.
- [x] Fix and merge #467.
- [ ] Merge #516.
- [ ] Set up GitHub pages to contain the API documentation.

### CODE REVIEW

**Comment by Ruin0x11** [comment]
Here is one benchmark, compiled under Release with no Lua-related things loaded:

Ran on Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz.

There doesn't seem to be much difference.

**Comment by Ruin0x11** [comment]
@ki-foobar The main changes are finished and tested. We could hold off merging this until the other bugs are fixed.

**Comment by ki-foobar** [comment]
I'll review and merge it this weekend.

**Comment by Ruin0x11** [comment]
One of the tests for FOV of characters broke. It might have been due to c422bb73c69dfafc8efdd094f76bf14a3735e2f2, but I'm not sure.

**Comment by Ruin0x11** [comment]
Seems to be because of a bug in removing character data from the map. In the test that fails, the character that is added is 5 spaces from the player. But when checking the player's line of sight, it finds an extra character.

```
Before 25 25 24 25                                                                                                                                                                       
Before 25 25 25 25                                                                                                                                                                       
LOS ダルレス                                                                                                                                                                             
Before 25 25 26 25                                                                                                                                                                       
LOS プチ                                                                                                                                                                                 
Before 25 25 27 25  
```

**Comment by Ruin0x11** [comment]
Figured it out, I'll open a bugfix.

**Comment by ki-foobar** [comment]
Thank you a lot for your awesome work. Without your contribution, mod system would not been implemented very quickly.

**Pull request merged**
