### PR TITLE
Adjust keywait for numpad wait/enter and shortcut key

### PR DESCRIPTION
**Pull request by Ruin0x11**
# Summary
- Adjusts the numpad wait and enter keys to be delayed.
- Adjusts shortcut keys to ~~never repeat~~ properly repeat.
- Increases delay on wait keypress.

### CODE REVIEW

**Comment by ki-foobar** [comment]
@Ruin0x11 

If shortcuts do not repeat, you cannot
- cast a spell repeatedly.
- eat food repeatedly.
- read scrolls repeatedly.

via shortcut key.

In Elona, players often do one action again and again so shortcut keys should be repeatable.

**Comment by Ruin0x11** [comment]
Makes sense, I'll make it repeatable. Although it seems like there was a strange issue with the shortcut key repeat to begin with. Before the player's main input `key_check(1)` is called. But this forced the delay to `1` instead of `keywait`. Should it be the opposite?

**Comment by ki-foobar** [comment]
> Makes sense, I'll make it repeatable. Although it seems like there was a strange issue with the shortcut key repeat to begin with. Before the player's main input key_check(1) is called. But this forced the delay to 1 instead of keywait because the input argument to key_check was 1. Should it be the opposite?

The previous key wait of shortcut keys were intended, but it seemed to be not good.

**Comment by ki-foobar** [comment]
Key response are very improved, thank you! Merging.

**Pull request merged**
