### PR TITLE
Add continuous integration and compile successfully across all platforms

### LINKED ISSUE #131: Introduce CI
TODO

### LINKED ISSUE #143: Include config.json in this repository
# Details

See also #141.

# Tasks

* [ ] Add `runtime/config.json`.
* [ ] Exclude `runtime/config.json` from `.gitignore`.
* [ ] Delete `runtime/config.json` from `README.md`.

### PR DESCRIPTION
**Pull request by Ruin0x11**
# Related Issues

Closes #131. Closes #143.

# Summary
Adds continuous integration for all three major platforms, and resolves issues preventing the game from running. Also automates as much of the build process as possible to allow for easily joining development.

## Building
- Added continuous integration testing for build success across Windows, macOS and Linux.
  + Binary artifacts are being produced for Windows. However, support is incomplete:
    + macOS and Linux currently do not have the proper dynamic libraries included, so they can't be run on arbitrary systems.
    + Assets from Elona 1.22 aren't automatically downloaded/copied on CI. We should investigate whether or not we are allowed do this.
    + Travis CI isn't set up to deploy artifacts to GitHub, so no artifacts are available for macOS and Linux.
- Added `cmake/FindSDL2.cmake`.
- Added a `runtime` folder with `config.json` and free/open license fonts (Bitstream Vera Sans, Kochi Gothic), which will reduce the friction needed to install.
- Added automatic copying of required asset folders from a provided `deps/elona` directory.
- Added automatic copying of dynamic libraries to output folder on Windows.
- Added automatic dependency downloading script for Windows.
- Added `ndata.csv`, `ndata-e.csv`, `name.csv`, `board.txt`, `book.txt`, `exhelp.txt` and `talk.txt` and converted all to UTF-8.
- Added missing flags `/MTd /ZI /Od` for MSVC debug target.
- Added Makefile for `nmake` on Windows.
- macOS build now outputs an .app bundle.

## Codebase
- Now compiles successfully on Windows and Linux.
- It is now possible to reach Vernis without freezing/crashing on all three platforms.
- Added a few `#define`s for some commonly used constants (max NPC count, etc).
- Uncaught errors on Windows are now reported through a dialog window and debug output instead of being silently ignored.
  + Cross-platform GUI support will be a separate change.
- Added `boost_iostreams` for `boost::iostreams::gzip_decompressor()` because map/save files were not being decompressed with `zlib`, causing corrupted data to be loaded.
- Added sanity checks for file existence when loading save files and Lua data files.
- Added automatic creation of `tmp` and `save` dirs.

### CODE REVIEW

**Comment by Ruin0x11** [comment]
@ki-foobar rebase is done, now I'm just trying to get the Linux CI to pass.

**Comment by Ruin0x11** [comment]
@ki-foobar Seems like CI passes for all three systems now.

**Comment by ki-foobar** [comment]
I searched about `font/Kochi Gothic.ttf`, its license seems to be not clear.
According to [this page](https://en.wikipedia.org/wiki/Kochi_font), this font is plagiarism. Because this incident occurred 15 years ago, so I could not investigate more. However, this vague licensed font should not be included in this project at least.
Thus, could you delete the commit where the font was added?
I agree with adding free font in this repository, so I'll find and add another free font.

Thanks for your contributing.

**Comment by Ruin0x11** [comment]
Actually I used the version of the font without any plagarised characters, `kochi-gothic-subst`. It's confusing since both fonts share the same name. If this is still unsatisfactory I'll look for another Japanese font.

**Pull request merged**
